server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: alok
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  sql:
    init:
      mode: always
#  rabbitmq:
#    host: "localhost"
#    username: "guest"
#    password: "guest"
#    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
